services:
  ros2-tb3:
    image: urllib2/rosforge-tb3:latest
    ports:
      - "6080:80"
    environment:
      - USER=ubuntu
      - PASSWD=ubuntu
    mem_limit: 5g
    memswap_limit: 6g
    volumes:
      - ./ros_ws/src:/home/ubuntu/ros_ws/src
      - ./ros_ws/install:/home/ubuntu/ros_ws/install
      - ./ros_ws/build:/home/ubuntu/ros_ws/build
      - ./ros_ws/log:/home/ubuntu/ros_ws/log
    stdin_open: true
    tty: true
    restart: unless-stopped